CONFIG_INIT_DIR = Driver_Init/
CONFIG_INIT_PATH = $(SRC_PATH)Driver/Config/$(CONFIG_INIT_DIR)
CONFIG_INIT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(CONFIG_INIT_DIR)Config/
CONFIG_INIT_INC = \
	-I$(CONFIG_INIT_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Other_headers
