CONFIG_INIT_MODULE = Driver_Init
CONFIG_INIT_PATH = $(PRJ_PATH)Driver/Config/$(CONFIG_INIT_MODULE)/
CONFIG_INIT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(CONFIG_INIT_MODULE)/Config/
CONFIG_INIT_INC = \
	-I$(CONFIG_INIT_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Other_headers
