WATCHDOG_DIR = Watchdog/
WATCHDOG_PATH = $(SRC_PATH)Driver/Config/$(WATCHDOG_DIR)
WATCHDOG_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(WATCHDOG_DIR)
WATCHDOG_INC = \
	-I$(REGISTERS_PATH) \
	-I$(GENERAL_HEADERS_PATH) \
	-I$(INTERRUPT_PATH)