TIMER_DIR = Timer/
TIMER_PATH = $(SRC_PATH)Driver/Config/$(TIMER_DIR)
PWM_PATH = $(TIMER_PATH)PWM/
TIMER_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(TIMER_DIR)
TIMER_INC = \
	-I$(GPIO_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(REGISTERS_PATH) \
	-I$(GENERAL_HEADERS_PATH)
