TIMER_MODULE = Timer
TIMER_PATH = $(PRJ_PATH)Driver/Config/$(TIMER_MODULE)/
PWM_PATH = $(TIMER_PATH)PWM/
TIMER_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(TIMER_MODULE)/
TIMER_INC = \
	-I$(TIMER_PATH) \
	-I$(GPIO_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Registers \
	-I$(STATIC_INIT_PATH)../Other_headers
