INTERRUPT_MODULE = Interrupt
INTERRUPT_PATH = $(PRJ_PATH)Driver/Config/$(INTERRUPT_MODULE)/
INTERRUPT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(INTERRUPT_MODULE)/
INTERRUPT_INC = \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Registers \
	-I$(STATIC_INIT_PATH)../Other_headers \
	-I$(CONFIG_INIT_PATH) \
	-I$(GPIO_PATH) \
	-I$(UART_PATH) \
	-I$(CONTROL_PATH)
