INTERRUPT_DIR = Interrupt/
INTERRUPT_PATH = $(SRC_PATH)Driver/Config/$(INTERRUPT_DIR)
INTERRUPT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(INTERRUPT_DIR)
INTERRUPT_INC = \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Registers \
	-I$(STATIC_INIT_PATH)../General_headers \
	-I$(CONFIG_INIT_PATH) \
	-I$(GPIO_PATH) \
	-I$(UART_PATH) \
	-I$(CONTROL_PATH)
