ALGORITHM_DIR = Algorithm/
ALGORITHM_PATH = $(SRC_PATH)$(ALGORITHM_DIR)
ALGORITHM_OBJ_PATH = $(BUILD_RESULT_PATH)$(ALGORITHM_DIR)

QUEUE_DIR = queue/
QUEUE_PATH = $(ALGORITHM_PATH)$(QUEUE_DIR)
QUEUE_OBJ_PATH = $(ALGORITHM_OBJ_PATH)$(QUEUE_DIR)
QUEUE_INC = \
	-I$(GENERAL_HEADERS_PATH) \

DELAY_US_DIR = delay_us/
DELAY_US_PATH = $(ALGORITHM_PATH)$(DELAY_US_DIR)
DELAY_US_OBJ_PATH = $(ALGORITHM_OBJ_PATH)$(DELAY_US_DIR)
DELAY_US_INC = \
	-I$(GENERAL_HEADERS_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(REGISTERS_PATH)
