ALGORITHM_DIR = Algorithm/
ALGORITHM_PATH = $(SRC_PATH)$(ALGORITHM_DIR)
ALGORITHM_OBJ_PATH = $(BUILD_RESULT_PATH)$(ALGORITHM_DIR)

QUEUE_DIR = queue/
QUEUE_PATH = $(ALGORITHM_PATH)$(QUEUE_DIR)
QUEUE_OBJ_PATH = $(ALGORITHM_OBJ_PATH)$(QUEUE_DIR)
QUEUE_INC = \
	-I$(GENERAL_HEADERS_PATH) \
	-I$(QUEUE_PATH)
	