DMA_DIR = DMA/
DMA_PATH = $(SRC_PATH)Driver/Config/$(DMA_DIR)
DMA_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(DMA_DIR)
DMA_INC = \
	-I$(INTERRUPT_PATH) \
	-I$(REGISTERS_PATH) \
	-I$(GENERAL_HEADERS_PATH)
