GPIO_MODULE = GPIO
GPIO_PATH = $(PRJ_PATH)Driver/Config/$(GPIO_MODULE)/
GPIO_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(GPIO_MODULE)/
GPIO_INC = \
	-I$(GPIO_PATH) \
	-I$(STATIC_INIT_PATH)../Other_headers \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Registers \
