STARTUP_CODE_DIR = StartupCode/
STARTUP_CODE_PATH = $(SRC_PATH)$(STARTUP_CODE_DIR)
STARTUP_CODE_OBJ_PATH = $(BUILD_RESULT_PATH)$(STARTUP_CODE_DIR)
STARTUP_CODE_INC = 	\
	-I$(STATIC_INIT_PATH)../General_headers \
	-I$(CONTROL_PATH) \
	-I$(CONFIG_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Registers \
	-I$(UART_PATH)
