STARTUP_CODE_DIR = StartupCode/
STARTUP_CODE_PATH = $(SRC_PATH)$(STARTUP_CODE_DIR)
STARTUP_CODE_OBJ_PATH = $(BUILD_RESULT_PATH)$(STARTUP_CODE_DIR)
STARTUP_CODE_INC = 	\
	-I$(GENERAL_HEADERS_PATH) \
	-I$(CONTROL_PATH) \
	-I$(CONFIG_INIT_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(REGISTERS_PATH) \
	-I$(GPIO_PATH) \
	-I$(TIMER_PATH) \
	-I$(QUEUE_PATH) \
	-I$(UART_PATH)
