CONTROL_MODULE = Control
CONTROL_PATH = $(PRJ_PATH)Hardware_Abstraction/$(CONTROL_MODULE)/
CONTROL_OBJ_PATH = $(BUILD_RESULT_PATH_HARDWARE_ABSTRACTION)$(CONTROL_MODULE)/
CONTROL_INC = \
	-I$(STATIC_INIT_PATH)../Other_headers \
	-I$(STATIC_INIT_PATH)../Registers \
	-I$(GPIO_PATH) \
	-I$(TIMER_PATH) \
	-I$(INTERRUPT_PATH) \
	-I$(UART_PATH) \
	