CONTROL_DIR = Control/
CONTROL_PATH = $(SRC_PATH)$(CONTROL_DIR)
CONTROL_OBJ_PATH = $(BUILD_RESULT_PATH)$(CONTROL_DIR)
CONTROL_INC = \
	-I$(UART_PATH) \
	-I$(QUEUE_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(GENERAL_HEADERS_PATH) \
	-I$(REGISTERS_PATH)
