CONTROL_DIR = Control/
CONTROL_PATH = $(SRC_PATH)$(CONTROL_DIR)
CONTROL_OBJ_PATH = $(BUILD_RESULT_PATH)$(CONTROL_DIR)
CONTROL_INC = \
	-I$(GPIO_PATH) \
	-I$(UART_PATH) \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../General_headers \
	-I$(STATIC_INIT_PATH)../Registers
