STATIC_INIT_DIR = Driver_Init/
GENERAL_HEADERS_DIR = General_headers/
REGISTERS_DIR = Registers/
STATIC_INIT_PATH = $(SRC_PATH)Driver/Static/$(STATIC_INIT_DIR)
GENERAL_HEADERS_PATH = $(SRC_PATH)Driver/Static/$(GENERAL_HEADERS_DIR)
REGISTERS_PATH = $(SRC_PATH)Driver/Static/$(REGISTERS_DIR)
STATIC_INIT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(STATIC_INIT_DIR)Static/
STATIC_INIT_INC = \
	-I$(GENERAL_HEADERS_PATH) \
	-I$(REGISTERS_PATH)
