STATIC_INIT_DIR = Driver_Init/
STATIC_INIT_PATH = $(SRC_PATH)Driver/Static/$(STATIC_INIT_DIR)
STATIC_INIT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(STATIC_INIT_DIR)Static/
STATIC_INIT_INC = \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../General_headers \
	-I$(STATIC_INIT_PATH)../Registers
