STATIC_INIT_MODULE = Driver_Init
STATIC_INIT_PATH = $(PRJ_PATH)Driver/Static/$(STATIC_INIT_MODULE)/
STATIC_INIT_OBJ_PATH = $(BUILD_RESULT_PATH_DRIVER)$(STATIC_INIT_MODULE)/Static/
STATIC_INIT_INC = \
	-I$(STATIC_INIT_PATH) \
	-I$(STATIC_INIT_PATH)../Other_headers \
	-I$(STATIC_INIT_PATH)../Registers
